version: 2

defaults: &defaults
  docker:
    - image: circleci/openjdk:8-jdk
      environment:
        # Customize the JVM maximum heap limit
        JVM_OPTS: -Xmx3200m
        TERM: dumb

references:
  workspace_root: &workspace_root
    /home/circleci/project
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      
      - run:
          name: Download codeclimate test reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

  build:
    <<: *defaults
    steps:
      - *attach_workspace

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: 
          name: Setup dependencies
          command: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # build (by default, test) and generate test report
      - run: 
          name: Build, test and generate test report
          command: gradle build jacocoTestReport

      - run:
          name: Code climate with jacoco
          command: |
            JACOCO_SOURCE_PATH=src/main/java ./cc-test-reporter format-coverage ./build/reports/jacoco/test/jacocoTestReport.xml --input-type jacoco

      - run:
          name: Upload code climate report
          command: ./cc-test-reporter upload-coverage -r $CC_TEST_REPORTER_ID
          when: on_success